const router = require('express').Router();
const swaggerUi = require('swagger-ui-express');
//load the swagger.json file that was generated by swagger.js
const swaggerDocument = require('../swagger.json');

router.use('/', swaggerUi.serve);
router.get('/', swaggerUi.setup(swaggerDocument));

module.exports = router;
